version: '3.8'
services:
  frontend:
    build:
      context: .
      args:
        - NEXT_PUBLIC_API_URL=https://baslimbus.store
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://baslimbus.store
    restart: unless-stopped
