version: '3.8'
services:
  frontend:
    build:
      context: .
      args:
        - NEXT_PUBLIC_API_URL=https://baslimbus.store
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://baslimbus.store
<<<<<<< HEAD
    restart: unless-stopped
=======
    restart: unless-stopped
>>>>>>> ae2d87a15d1dca47061c0715e9b51c2e50659593
